# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- ODBC

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: amd64
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'push to docker'
        command: 'buildAndPush'
        repository: 'nicho267/anythingllm'
        dockerfile: '$(Build.SourcesDirectory)/docker/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: ODBC-latest
